GET http://localhost:3333/products?manufacturerId=1&stock=5

###

POST http://localhost:3333/products
content-type: application/json

{
    "name": "iPad Pro",
    "price": "8899.00",
    "stock": 20,
    "manufacturerId": 1
}

###

PUT http://localhost:3333/products/9
content-type: application/json

{ "price": 10999.00, "stock": 10 }

###

DELETE http://localhost:3333/products/17
