GET http://localhost:3333/users

###

POST http://localhost:3333/users
content-type: application/json
Authorization: Bearer NQ.HTAq45GRHwW3GockmUej4cLPKj3ILRz-2aUgIggl2ymNPJFsXMlqVotb04a-

{
    "email": "uedson",
    "password": "123"
}

###

POST http://localhost:3333/login
content-type: application/json

{
    "email": "admin",
    "password": "admin"
}

###

GET http://localhost:3333/logged
Authorization: Bearer NQ.HTAq45GRHwW3GockmUej4cLPKj3ILRz-2aUgIggl2ymNPJFsXMlqVotb04a-

###

DELETE http://localhost:3333/login
Authorization: Bearer NQ.HTAq45GRHwW3GockmUej4cLPKj3ILRz-2aUgIggl2ymNPJFsXMlqVotb04a-