
POST http://localhost:3333/login
content-type: application/json

{
    "email": "admin",
    "password": "admin"
}

###

GET http://localhost:3333/logged
Authorization: Bearer NA.ZaO6cGGlYGQr-nsNlZJ852_zl49OqiJHEFV2W-bj4TMocItVlg35TDqU1KKp