GET http://localhost:3333/users
Authorization: Bearer Ng.fYVw9U-X50lKhMZECwrAGjXoy8AJL3gDRiT7UUYyVAN47GZkVzxVf34sJFp3

###

POST http://localhost:3333/users
content-type: application/json
Authorization: Bearer OA.yY-wNkt-FnnuA5claf0XltsCrortesCA119adfNeSJmZtGL2EZ2ko8W2pVNw

{
    "email": "uedson",
    "password": "123"
}

###

POST http://localhost:3333/login
content-type: application/json

{
    "email": "admin",
    "password": "admin"
}

###

GET http://localhost:3333/logged
Authorization: Bearer OA.yY-wNkt-FnnuA5claf0XltsCrortesCA119adfNeSJmZtGL2EZ2ko8W2pVNw

###

DELETE http://localhost:3333/login
Authorization: Bearer OA.yY-wNkt-FnnuA5claf0XltsCrortesCA119adfNeSJmZtGL2EZ2ko8W2pVNw