GET http://localhost:3333/users
Authorization: Bearer MQ.oGNsObjlOpr_OlmGFdOuPrwHZWha0VIJ6UdIjvLZVYnidl1TzCH2PnAl0jT1

###

POST http://localhost:3333/users
content-type: application/json
Authorization: Bearer OA.yY-wNkt-FnnuA5claf0XltsCrortesCA119adfNeSJmZtGL2EZ2ko8W2pVNw

{
    "email": "uedson",
    "password": "123"
}

###

POST http://localhost:3333/login
content-type: application/json

{
    "email": "admin",
    "password": "admin"
}

###

GET http://localhost:3333/login
Authorization: Bearer OA.yY-wNkt-FnnuA5claf0XltsCrortesCA119adfNeSJmZtGL2EZ2ko8W2pVNw

###

DELETE http://localhost:3333/login
Authorization: Bearer OA.yY-wNkt-FnnuA5claf0XltsCrortesCA119adfNeSJmZtGL2EZ2ko8W2pVNw